using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace LXFramework.Tools;

internal static partial class ContentGenerator
{
    private const string ManifestRelativePath = "content/data/content-manifest.json";

    public static IReadOnlyDictionary<string, string> BuildOutputs(string root)
    {
        var path = Path.Combine(root, ManifestRelativePath.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(path))
        {
            throw new FileNotFoundException("Content manifest is missing.", path);
        }

        var manifest = ToolFiles.ReadJson<ContentManifest>(path);
        var game = ToolFiles.ReadJson<GameManifest>(
            Path.Combine(root, "content", "game", "game-manifest.json"));
        Validate(root, manifest, game);
        if (manifest.Tables.Count == 0)
        {
            return new Dictionary<string, string>(StringComparer.Ordinal);
        }

        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [Path.Combine(ProductLayout.GetGeneratedDirectory(root, game), "ContentCatalog.g.cs")] =
                BuildCatalog(manifest, game),
        };
    }

    private static void Validate(string root, ContentManifest manifest, GameManifest game)
    {
        if (manifest.Version != 1)
        {
            throw new InvalidDataException($"Unsupported content manifest version {manifest.Version}.");
        }

        var ids = new HashSet<string>(StringComparer.Ordinal);
        var properties = new HashSet<string>(StringComparer.Ordinal);
        foreach (var table in manifest.Tables)
        {
            ManifestScopes.Require(table.Scope, "Content table", table.Id);
            CodeNames.RequireSnakeCase(table.Id, nameof(table.Id));
            CodeNames.RequireIdentifier(table.ClassName, nameof(table.ClassName));
            if (table.Scope != ManifestScopes.Product ||
                !NamespaceRegex().IsMatch(table.Namespace) ||
                !ProductLayout.IsProductNamespace(game, table.Namespace))
            {
                throw new InvalidDataException(
                    $"Content table '{table.Id}' must use Product scope and namespace '{game.RootNamespace}'.");
            }
            if (!ids.Add(table.Id))
            {
                throw new InvalidDataException($"Content table ID '{table.Id}' is duplicated.");
            }
            if (!properties.Add(CodeNames.ToPascalCase(table.Id)))
            {
                throw new InvalidDataException($"Content table ID '{table.Id}' has a generated name collision.");
            }
            if (!table.Path.StartsWith("res://content/data/", StringComparison.Ordinal) ||
                !table.Path.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidDataException($"Content table '{table.Id}' has invalid path '{table.Path}'.");
            }
            var dataPath = ToolFiles.ToAbsolutePath(root, table.Path);
            if (!File.Exists(dataPath))
            {
                throw new FileNotFoundException($"Content table '{table.Id}' data file is missing.");
            }

            using var document = JsonDocument.Parse(File.ReadAllText(dataPath));
            if (document.RootElement.ValueKind != JsonValueKind.Array)
            {
                throw new InvalidDataException($"Content table '{table.Id}' must contain a JSON array.");
            }
            var recordIds = new HashSet<string>(StringComparer.Ordinal);
            foreach (var record in document.RootElement.EnumerateArray())
            {
                if (record.ValueKind != JsonValueKind.Object)
                {
                    throw new InvalidDataException(
                        $"Content table '{table.Id}' entries must be JSON objects.");
                }
                if (record.TryGetProperty("id", out var idProperty))
                {
                    var id = idProperty.GetString();
                    if (string.IsNullOrWhiteSpace(id))
                    {
                        throw new InvalidDataException(
                            $"Content table '{table.Id}' contains an empty record ID.");
                    }
                    if (!recordIds.Add(id))
                    {
                        throw new InvalidDataException(
                            $"Content table '{table.Id}' contains duplicate record ID '{id}'.");
                    }
                }
            }
        }
    }

    private static string BuildCatalog(ContentManifest manifest, GameManifest game)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by LXFramework.Tools />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using LX.Content;");
        builder.AppendLine();
        builder.AppendLine($"namespace {game.RootNamespace}.Generated;");
        builder.AppendLine();
        builder.AppendLine("public static class ContentCatalog");
        builder.AppendLine("{");
        foreach (var table in manifest.Tables.OrderBy(table => table.Id, StringComparer.Ordinal))
        {
            builder.AppendLine(
                $"    public static readonly ContentRef<{table.Namespace}.{table.ClassName}[]> {CodeNames.ToPascalCase(table.Id)} = new(");
            builder.AppendLine($"        \"{Escape(table.Path)}\");");
            builder.AppendLine();
        }
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string Escape(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal);

    [GeneratedRegex("^[A-Za-z_][A-Za-z0-9_]*(\\.[A-Za-z_][A-Za-z0-9_]*)*$", RegexOptions.CultureInvariant)]
    private static partial Regex NamespaceRegex();
}
