using System.Text;
using System.Text.RegularExpressions;

namespace LXFramework.Tools;

internal static partial class FeatureGenerator
{
    private const string ManifestRelativePath = "content/features/feature-manifest.json";

    public static IReadOnlyDictionary<string, string> BuildOutputs(string root)
    {
        var path = Path.Combine(root, ManifestRelativePath.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(path))
        {
            throw new FileNotFoundException("Feature manifest is missing.", path);
        }

        var manifest = ToolFiles.ReadJson<FeatureManifest>(path);
        var game = ToolFiles.ReadJson<GameManifest>(
            Path.Combine(root, "content", "game", "game-manifest.json"));
        Validate(root, manifest, game);
        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [Path.Combine(root, "src", "LXFramework", "Generated", "FeatureCatalog.g.cs")] = BuildCatalog(manifest),
        };
    }

    private static void Validate(string root, FeatureManifest manifest, GameManifest game)
    {
        if (manifest.Version != 1)
        {
            throw new InvalidDataException($"Unsupported feature manifest version {manifest.Version}.");
        }

        var ids = new HashSet<string>(StringComparer.Ordinal);
        var properties = new HashSet<string>(StringComparer.Ordinal);
        foreach (var feature in manifest.Features)
        {
            ManifestScopes.Require(feature.Scope, "Feature", feature.Id);
            CodeNames.RequireSnakeCase(feature.Id, nameof(feature.Id));
            CodeNames.RequireIdentifier(feature.ClassName, nameof(feature.ClassName));
            var validNamespace = feature.Scope == ManifestScopes.Framework
                ? string.Equals(feature.Namespace, "LX", StringComparison.Ordinal) ||
                  feature.Namespace.StartsWith("LX.", StringComparison.Ordinal)
                : ProductLayout.IsProductNamespace(game, feature.Namespace);
            if (!NamespaceRegex().IsMatch(feature.Namespace) || !validNamespace)
            {
                throw new InvalidDataException(
                    $"Feature '{feature.Id}' namespace '{feature.Namespace}' does not match its {feature.Scope} scope.");
            }
            if (!ids.Add(feature.Id))
            {
                throw new InvalidDataException($"Feature ID '{feature.Id}' is duplicated.");
            }
            if (!properties.Add(CodeNames.ToPascalCase(feature.Id)))
            {
                throw new InvalidDataException($"Feature ID '{feature.Id}' has a generated name collision.");
            }
            if (!feature.ScenePath.StartsWith("res://scene/features/", StringComparison.Ordinal) ||
                !feature.ScenePath.EndsWith(".tscn", StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidDataException($"Feature '{feature.Id}' has invalid path '{feature.ScenePath}'.");
            }
            if (!File.Exists(ToolFiles.ToAbsolutePath(root, feature.ScenePath)))
            {
                throw new FileNotFoundException($"Feature '{feature.Id}' scene is missing.");
            }
        }
    }

    private static string BuildCatalog(FeatureManifest manifest)
    {
        var features = manifest.Features.OrderBy(feature => feature.Id, StringComparer.Ordinal).ToArray();
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by LXFramework.Tools />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using LX.Features;");
        builder.AppendLine();
        builder.AppendLine("namespace LX.Generated;");
        builder.AppendLine();
        builder.AppendLine("public static class FeatureCatalog");
        builder.AppendLine("{");
        foreach (var feature in features)
        {
            builder.AppendLine(
                $"    public static readonly FeatureDescriptor {CodeNames.ToPascalCase(feature.Id)} = new(");
            builder.AppendLine($"        new FeatureId(\"{Escape(feature.Id)}\"),");
            builder.AppendLine($"        \"{Escape(feature.ScenePath)}\");");
            builder.AppendLine();
        }
        builder.Append("    public static IReadOnlyList<FeatureDescriptor> All { get; } = [");
        builder.Append(string.Join(", ", features.Select(feature => CodeNames.ToPascalCase(feature.Id))));
        builder.AppendLine("];\n}");
        return builder.ToString();
    }

    private static string Escape(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal);

    [GeneratedRegex("^[A-Za-z_][A-Za-z0-9_]*(\\.[A-Za-z_][A-Za-z0-9_]*)*$", RegexOptions.CultureInvariant)]
    private static partial Regex NamespaceRegex();
}
