using System.Text;
using System.Text.RegularExpressions;

namespace LXFramework.Tools;

internal static partial class InputGenerator
{
    private const string ManifestRelativePath = "content/input/input-manifest.json";

    public static IReadOnlyDictionary<string, string> BuildOutputs(string root)
    {
        var manifestPath = Path.Combine(root, ManifestRelativePath.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(manifestPath))
        {
            throw new FileNotFoundException("Input manifest is missing.", manifestPath);
        }

        var manifest = ToolFiles.ReadJson<InputManifest>(manifestPath);
        Validate(manifest);
        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [Path.Combine(root, "src", "LXFramework", "Generated", "InputCatalog.g.cs")] = BuildCatalog(manifest),
            [Path.Combine(root, "src", "LXFramework", "Generated", "LXInputActions.g.cs")] = BuildFacade(manifest),
        };
    }

    private static void Validate(InputManifest manifest)
    {
        if (manifest.Version != 1)
        {
            throw new InvalidDataException($"Unsupported input manifest version {manifest.Version}.");
        }

        var actionIds = new HashSet<string>(StringComparer.Ordinal);
        var propertyNames = new HashSet<string>(StringComparer.Ordinal);
        var godotActions = new HashSet<string>(StringComparer.Ordinal);
        foreach (var action in manifest.Actions)
        {
            ManifestScopes.Require(action.Scope, "Input action", action.Id);
            CodeNames.RequireSnakeCase(action.Id, nameof(action.Id));
            if (!actionIds.Add(action.Id))
            {
                throw new InvalidDataException($"Input action ID '{action.Id}' is duplicated.");
            }
            if (!propertyNames.Add(CodeNames.ToPascalCase(action.Id)))
            {
                throw new InvalidDataException($"Input action ID '{action.Id}' has a generated name collision.");
            }
            if (action.Routes.Count == 0)
            {
                throw new InvalidDataException($"Input action '{action.Id}' must declare at least one Godot route.");
            }

            foreach (var route in action.Routes)
            {
                if (!GodotActionRegex().IsMatch(route.GodotAction))
                {
                    throw new InvalidDataException(
                        $"Input action '{action.Id}' has invalid Godot action '{route.GodotAction}'.");
                }
                if (!godotActions.Add(route.GodotAction))
                {
                    throw new InvalidDataException($"Godot input action '{route.GodotAction}' is routed more than once.");
                }
                if (route.DefaultPhysicalKey is not null)
                {
                    CodeNames.RequireIdentifier(route.DefaultPhysicalKey, nameof(route.DefaultPhysicalKey));
                }
            }
        }
    }

    private static string BuildCatalog(InputManifest manifest)
    {
        var actions = manifest.Actions.OrderBy(action => action.Id, StringComparer.Ordinal).ToArray();
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by LXFramework.Tools />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using Godot;");
        builder.AppendLine("using LX.Input;");
        builder.AppendLine();
        builder.AppendLine("namespace LX.Generated;");
        builder.AppendLine();
        builder.AppendLine("public static class InputCatalog");
        builder.AppendLine("{");
        foreach (var action in actions)
        {
            builder.AppendLine(
                $"    public static readonly InputActionId {CodeNames.ToPascalCase(action.Id)} = new(\"{Escape(action.Id)}\");");
        }

        builder.AppendLine();
        builder.AppendLine("    public static IReadOnlyList<InputRouteDescriptor> All { get; } =");
        builder.AppendLine("    [");
        foreach (var action in actions)
        {
            foreach (var route in action.Routes.OrderBy(route => route.GodotAction, StringComparer.Ordinal))
            {
                var key = route.DefaultPhysicalKey is null
                    ? string.Empty
                    : $", Key.{route.DefaultPhysicalKey}";
                builder.AppendLine(
                    $"        new({CodeNames.ToPascalCase(action.Id)}, \"{Escape(route.GodotAction)}\"{key}),");
            }
        }
        builder.AppendLine("    ];");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildFacade(InputManifest manifest)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by LXFramework.Tools />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using LX.Generated;");
        builder.AppendLine();
        builder.AppendLine("namespace LX.Input;");
        builder.AppendLine();
        builder.AppendLine("public static class LXInputActions");
        builder.AppendLine("{");
        foreach (var action in manifest.Actions.OrderBy(action => action.Id, StringComparer.Ordinal))
        {
            var name = CodeNames.ToPascalCase(action.Id);
            builder.AppendLine($"    public static InputActionId {name} => InputCatalog.{name};");
        }
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string Escape(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal);

    [GeneratedRegex("^[A-Za-z0-9_./:-]+$", RegexOptions.CultureInvariant)]
    private static partial Regex GodotActionRegex();
}
