namespace LXFramework.Tools;

internal static class ProjectGenerator
{
    public static int Run(string root, IReadOnlyList<string>? arguments = null)
    {
        var verbose = arguments?.Contains("--verbose", StringComparer.OrdinalIgnoreCase) == true;
        if (arguments?.Any(argument => !string.Equals(argument, "--verbose", StringComparison.OrdinalIgnoreCase)) == true)
        {
            throw new ArgumentException("generate accepts only --verbose.");
        }

        var outputs = BuildOutputs(root);
        var removed = PruneOrphanedOutputs(root, outputs.Keys);
        var changed = new List<string>();
        foreach (var output in outputs)
        {
            if (ToolFiles.WriteText(output.Key, output.Value))
            {
                changed.Add(ToolFiles.Relative(root, output.Key));
            }
        }

        if (verbose)
        {
            foreach (var path in changed)
            {
                Console.WriteLine($"generated {path}");
            }
            foreach (var path in removed)
            {
                Console.WriteLine($"removed orphan {path}");
            }
        }

        Console.WriteLine(
            $"generation passed: {outputs.Count} outputs, {changed.Count} changed, {removed.Count} removed");
        return 0;
    }

    public static IReadOnlyDictionary<string, string> BuildOutputs(string root)
    {
        var outputs = new SortedDictionary<string, string>(StringComparer.Ordinal);
        Add(outputs, ContentGenerator.BuildOutputs(root));
        Add(outputs, FeatureGenerator.BuildOutputs(root));
        Add(outputs, GameGenerator.BuildOutputs(root));
        Add(outputs, InputGenerator.BuildOutputs(root));
        Add(outputs, UIGenerator.BuildOutputs(root));
        Add(outputs, ResGenerator.BuildOutputs(root));
        return outputs;
    }

    private static IReadOnlyList<string> PruneOrphanedOutputs(
        string root,
        IEnumerable<string> expectedPaths)
    {
        var comparison = OperatingSystem.IsWindows()
            ? StringComparer.OrdinalIgnoreCase
            : StringComparer.Ordinal;
        var expected = expectedPaths.Select(Path.GetFullPath).ToHashSet(comparison);
        var game = ToolFiles.ReadJson<GameManifest>(
            Path.Combine(root, "content", "game", "game-manifest.json"));
        var generatedRoots = new List<string>
        {
            Path.Combine(root, "src", "LXFramework", "Generated"),
        };
        if (!string.IsNullOrWhiteSpace(game.Name))
        {
            generatedRoots.Add(ProductLayout.GetGeneratedDirectory(root, game));
        }
        var removed = new List<string>();

        foreach (var generatedRoot in generatedRoots.Where(Directory.Exists))
        {
            foreach (var path in Directory.EnumerateFiles(generatedRoot, "*.g.cs", SearchOption.AllDirectories))
            {
                if (expected.Contains(Path.GetFullPath(path)))
                {
                    continue;
                }

                var content = File.ReadAllText(path);
                if (!content.StartsWith("// <auto-generated by LXFramework.Tools />", StringComparison.Ordinal))
                {
                    throw new InvalidDataException(
                        $"Refusing to remove unrecognized generated file '{ToolFiles.Relative(root, path)}'.");
                }

                File.Delete(path);
                var uidPath = path + ".uid";
                if (File.Exists(uidPath))
                {
                    File.Delete(uidPath);
                }
                removed.Add(ToolFiles.Relative(root, path));
            }

            foreach (var uidPath in Directory.EnumerateFiles(generatedRoot, "*.g.cs.uid", SearchOption.AllDirectories))
            {
                var sourcePath = uidPath[..^".uid".Length];
                if (expected.Contains(Path.GetFullPath(sourcePath)) || File.Exists(sourcePath))
                {
                    continue;
                }

                File.Delete(uidPath);
                removed.Add(ToolFiles.Relative(root, uidPath));
            }
        }

        return removed;
    }

    private static void Add(
        IDictionary<string, string> destination,
        IReadOnlyDictionary<string, string> source)
    {
        foreach (var output in source)
        {
            if (!destination.TryAdd(output.Key, output.Value))
            {
                throw new InvalidOperationException($"Multiple generators target '{output.Key}'.");
            }
        }
    }
}
