using System.Text;
using System.Text.RegularExpressions;

namespace LXFramework.Tools;

internal static partial class ResGenerator
{
    private const string ManifestRelativePath = "content/res/res-manifest.json";

    public static IReadOnlyDictionary<string, string> BuildOutputs(string root)
    {
        var manifestPath = Path.Combine(root, ManifestRelativePath.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(manifestPath))
        {
            throw new FileNotFoundException("Resource manifest is missing.", manifestPath);
        }

        var manifest = ToolFiles.ReadJson<AssetManifest>(manifestPath);
        if (manifest.Version != 1)
        {
            throw new InvalidDataException($"Unsupported resource manifest version {manifest.Version}.");
        }

        var duplicate = manifest.Assets
            .GroupBy(asset => asset.Id, StringComparer.Ordinal)
            .FirstOrDefault(group => group.Count() > 1);
        if (duplicate is not null)
        {
            throw new InvalidDataException($"Resource ID '{duplicate.Key}' is duplicated.");
        }

        var generatedNameCollision = manifest.Assets
            .GroupBy(asset => CodeNames.ToPascalCase(asset.Id), StringComparer.Ordinal)
            .FirstOrDefault(group => group.Count() > 1);
        if (generatedNameCollision is not null)
        {
            throw new InvalidDataException(
                $"Resource IDs collide as generated name '{generatedNameCollision.Key}'.");
        }

        foreach (var asset in manifest.Assets)
        {
            Validate(root, asset);
        }

        ValidateGroups(manifest);

        var output = Path.Combine(root, "src", "LXFramework", "Generated", "ResCatalog.g.cs");
        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [output] = BuildCatalog(manifest),
        };
    }

    private static string BuildCatalog(AssetManifest manifest)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by LXFramework.Tools />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using LX.Res;");
        builder.AppendLine("using Godot;");
        builder.AppendLine();
        builder.AppendLine("namespace LX.Generated;");
        builder.AppendLine();
        builder.AppendLine("public static class ResCatalog");
        builder.AppendLine("{");
        foreach (var asset in manifest.Assets.OrderBy(asset => asset.Id, StringComparer.Ordinal))
        {
            builder.AppendLine(
                $"    public static readonly AssetRef<{asset.ResourceType}> {CodeNames.ToPascalCase(asset.Id)} = new(");
            builder.AppendLine($"        \"{Escape(asset.Path)}\",");
            builder.AppendLine($"        AssetCachePolicy.{asset.CachePolicy});");
            builder.AppendLine();
        }

        var groups = manifest.Assets
            .Where(asset => !string.IsNullOrWhiteSpace(asset.Group))
            .GroupBy(asset => asset.Group!, StringComparer.Ordinal)
            .OrderBy(group => group.Key, StringComparer.Ordinal)
            .ToArray();
        if (groups.Length > 0)
        {
            builder.AppendLine("    public static class Groups");
            builder.AppendLine("    {");
            foreach (var group in groups)
            {
                var resourceType = group.First().ResourceType;
                builder.AppendLine(
                    $"        public static readonly AssetGroup<{resourceType}> {CodeNames.ToPascalCase(group.Key)} = new(");
                var groupedAssets = group.OrderBy(asset => asset.Id, StringComparer.Ordinal).ToArray();
                for (var index = 0; index < groupedAssets.Length; index++)
                {
                    var asset = groupedAssets[index];
                    var suffix = index + 1 == groupedAssets.Length ? string.Empty : ",";
                    builder.AppendLine(
                        $"            (\"{Escape(asset.Id)}\", {CodeNames.ToPascalCase(asset.Id)}){suffix}");
                }
                builder.AppendLine("        );");
                builder.AppendLine();
            }
            builder.AppendLine("    }");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void Validate(string root, AssetManifestEntry asset)
    {
        ManifestScopes.Require(asset.Scope, "Resource", asset.Id);
        CodeNames.RequireSnakeCase(asset.Id, nameof(asset.Id));
        if (!ResourceTypeRegex().IsMatch(asset.ResourceType))
        {
            throw new InvalidDataException($"Resource '{asset.Id}' has invalid resource type '{asset.ResourceType}'.");
        }

        if (asset.CachePolicy is not ("Transient" or "Cached" or "Resident"))
        {
            throw new InvalidDataException($"Resource '{asset.Id}' has invalid cache policy '{asset.CachePolicy}'.");
        }
        if (asset.Group is not null)
        {
            CodeNames.RequireSnakeCase(asset.Group, nameof(asset.Group));
        }

        var path = ToolFiles.ToAbsolutePath(root, asset.Path);
        if (!File.Exists(path))
        {
            throw new FileNotFoundException($"Resource '{asset.Id}' points to missing path '{asset.Path}'.", path);
        }
    }

    private static void ValidateGroups(AssetManifest manifest)
    {
        foreach (var group in manifest.Assets
                     .Where(asset => !string.IsNullOrWhiteSpace(asset.Group))
                     .GroupBy(asset => asset.Group!, StringComparer.Ordinal))
        {
            var resourceTypes = group
                .Select(asset => asset.ResourceType)
                .Distinct(StringComparer.Ordinal)
                .ToArray();
            if (resourceTypes.Length != 1)
            {
                throw new InvalidDataException(
                    $"Resource group '{group.Key}' mixes resource types: {string.Join(", ", resourceTypes)}.");
            }
        }

        var generatedNameCollision = manifest.Assets
            .Where(asset => !string.IsNullOrWhiteSpace(asset.Group))
            .Select(asset => asset.Group!)
            .Distinct(StringComparer.Ordinal)
            .GroupBy(CodeNames.ToPascalCase, StringComparer.Ordinal)
            .FirstOrDefault(group => group.Count() > 1);
        if (generatedNameCollision is not null)
        {
            throw new InvalidDataException(
                $"Resource groups collide as generated name '{generatedNameCollision.Key}'.");
        }
    }

    private static string Escape(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal);

    [GeneratedRegex("^[A-Za-z_][A-Za-z0-9_.]*$", RegexOptions.CultureInvariant)]
    private static partial Regex ResourceTypeRegex();
}
