using System.Text;
using System.Text.RegularExpressions;

namespace LXFramework.Tools;

internal static partial class UIGenerator
{
    private const string ManifestRelativePath = "content/ui/ui-manifest.json";
    private const string GeneratedDirectory = "src/LXFramework/Generated";

    public static int Run(string root)
    {
        var outputs = BuildOutputs(root);
        foreach (var output in outputs)
        {
            ToolFiles.WriteText(output.Key, output.Value);
            Console.WriteLine($"generated {ToolFiles.Relative(root, output.Key)}");
        }

        Console.WriteLine($"LXFramework generated {outputs.Count} deterministic file(s).");
        return 0;
    }

    public static IReadOnlyDictionary<string, string> BuildOutputs(string root)
    {
        var manifestPath = Path.Combine(root, ManifestRelativePath.Replace('/', Path.DirectorySeparatorChar));
        if (!File.Exists(manifestPath))
        {
            throw new FileNotFoundException("UI manifest is missing.", manifestPath);
        }

        var manifest = ToolFiles.ReadJson<UIManifest>(manifestPath);
        var game = ToolFiles.ReadJson<GameManifest>(
            Path.Combine(root, "content", "game", "game-manifest.json"));
        if (manifest.Version != 1)
        {
            throw new InvalidDataException($"Unsupported UI manifest version {manifest.Version}.");
        }

        var outputs = new SortedDictionary<string, string>(StringComparer.Ordinal);
        foreach (var entry in manifest.Screens.OrderBy(screen => screen.Id, StringComparer.Ordinal))
        {
            ValidateEntry(entry, game);
            var scenePath = ToolFiles.ToAbsolutePath(root, entry.ScenePath);
            if (!File.Exists(scenePath))
            {
                throw new FileNotFoundException($"UI scene '{entry.ScenePath}' does not exist.", scenePath);
            }

            var scene = TscnParser.Parse(scenePath);
            var uniqueNodes = scene.Nodes.Where(node => node.UniqueNameInOwner).ToArray();
            var untyped = uniqueNodes.FirstOrDefault(node => !node.HasExplicitType);
            if (untyped is not null)
            {
                throw new InvalidDataException(
                    $"Scene '{entry.ScenePath}' code-bound node '{untyped.Name}' must declare an explicit type; " +
                    "bind a typed wrapper instead of an instanced-scene placeholder.");
            }
            var duplicate = uniqueNodes.GroupBy(node => node.Name, StringComparer.Ordinal)
                .FirstOrDefault(group => group.Count() > 1);
            if (duplicate is not null)
            {
                throw new InvalidDataException(
                    $"Scene '{entry.ScenePath}' has duplicate unique node name '{duplicate.Key}'.");
            }
            var generatedNameCollision = uniqueNodes.GroupBy(node => ToIdentifier(node.Name), StringComparer.Ordinal)
                .FirstOrDefault(group => group.Count() > 1);
            if (generatedNameCollision is not null)
            {
                throw new InvalidDataException(
                    $"Scene '{entry.ScenePath}' has code-bound node names that collide as " +
                    $"'{generatedNameCollision.Key}'.");
            }

            var bindingDirectory = entry.Scope == ManifestScopes.Product
                ? ProductLayout.GetGeneratedDirectory(root, game)
                : Path.Combine(root, GeneratedDirectory);
            var bindingPath = Path.Combine(bindingDirectory, $"{entry.ClassName}.Bindings.g.cs");
            outputs.Add(bindingPath, BuildBindings(entry, uniqueNodes));
        }

        outputs.Add(Path.Combine(root, GeneratedDirectory, "UICatalog.g.cs"), BuildCatalog(manifest));
        return outputs;
    }

    private static string BuildBindings(UIManifestEntry entry, IReadOnlyList<TscnNode> nodes)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by LXFramework.Tools />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using Godot;");
        builder.AppendLine();
        builder.AppendLine($"namespace {entry.Namespace};");
        builder.AppendLine();
        builder.AppendLine($"public partial class {entry.ClassName}");
        builder.AppendLine("{");
        foreach (var node in nodes)
        {
            builder.AppendLine(
                $"    protected {node.Type} {ToIdentifier(node.Name)} {{ get; private set; }} = null!;");
        }

        if (nodes.Count > 0)
        {
            builder.AppendLine();
        }

        builder.AppendLine("    protected override void BindGeneratedNodes()");
        builder.AppendLine("    {");
        foreach (var node in nodes)
        {
            builder.AppendLine(
                $"        {ToIdentifier(node.Name)} = GetNode<{node.Type}>(\"%{Escape(node.Name)}\");");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildCatalog(UIManifest manifest)
    {
        var entries = manifest.Screens.OrderBy(screen => screen.Id, StringComparer.Ordinal).ToArray();
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated by LXFramework.Tools />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using LX.UI;");
        builder.AppendLine();
        builder.AppendLine("namespace LX.Generated;");
        builder.AppendLine();
        builder.AppendLine("public static class UICatalog");
        builder.AppendLine("{");
        foreach (var entry in entries)
        {
            builder.AppendLine($"    public static readonly UIDescriptor {ToIdentifier(entry.ClassName.Replace("Screen", string.Empty, StringComparison.Ordinal))} = new(");
            builder.AppendLine($"        new UIId(\"{Escape(entry.Id)}\"),");
            builder.AppendLine($"        \"{Escape(entry.ScenePath)}\",");
            builder.AppendLine($"        UILayer.{entry.Layer},");
            builder.AppendLine($"        UICachePolicy.{entry.CachePolicy},");
            builder.AppendLine($"        UICoverPolicy.{entry.CoverPolicy},");
            builder.AppendLine($"        UIInputPolicy.{entry.InputPolicy},");
            builder.AppendLine($"        UIFocusPolicy.{entry.FocusPolicy});");
            builder.AppendLine();
        }

        builder.Append("    public static IReadOnlyList<UIDescriptor> All { get; } = [");
        builder.Append(string.Join(", ", entries.Select(entry => ToIdentifier(entry.ClassName.Replace("Screen", string.Empty, StringComparison.Ordinal)))));
        builder.AppendLine("];\n}");
        return builder.ToString();
    }

    private static void ValidateEntry(UIManifestEntry entry, GameManifest game)
    {
        ManifestScopes.Require(entry.Scope, "UI", entry.Id);
        if (!IdRegex().IsMatch(entry.Id))
        {
            throw new InvalidDataException($"UI ID '{entry.Id}' must be lowercase snake_case.");
        }

        if (!IdentifierRegex().IsMatch(entry.ClassName) || !NamespaceRegex().IsMatch(entry.Namespace))
        {
            throw new InvalidDataException($"UI '{entry.Id}' has an invalid class or namespace.");
        }
        var validNamespace = entry.Scope == ManifestScopes.Framework
            ? string.Equals(entry.Namespace, "LX", StringComparison.Ordinal) ||
              entry.Namespace.StartsWith("LX.", StringComparison.Ordinal)
            : ProductLayout.IsProductNamespace(game, entry.Namespace);
        if (!validNamespace)
        {
            throw new InvalidDataException(
                $"UI '{entry.Id}' namespace '{entry.Namespace}' does not match its {entry.Scope} scope.");
        }

        if (entry.Layer is not ("Screen" or "Popup" or "Overlay"))
        {
            throw new InvalidDataException($"UI '{entry.Id}' has unsupported layer '{entry.Layer}'.");
        }

        if (entry.CachePolicy is not ("Transient" or "CachedSingleton"))
        {
            throw new InvalidDataException($"UI '{entry.Id}' has unsupported cache policy '{entry.CachePolicy}'.");
        }

        if (entry.CoverPolicy is not ("KeepVisible" or "HidePrevious" or "ClosePrevious"))
        {
            throw new InvalidDataException($"UI '{entry.Id}' has unsupported cover policy '{entry.CoverPolicy}'.");
        }

        if (entry.InputPolicy is not ("Normal" or "Modal"))
        {
            throw new InvalidDataException($"UI '{entry.Id}' has unsupported input policy '{entry.InputPolicy}'.");
        }
        if (entry.FocusPolicy is not ("Preserve" or "GrabFirst"))
        {
            throw new InvalidDataException($"UI '{entry.Id}' has unsupported focus policy '{entry.FocusPolicy}'.");
        }
    }

    private static string ToIdentifier(string value)
    {
        var parts = NonIdentifierRegex().Split(value).Where(part => part.Length > 0).ToArray();
        var result = string.Concat(parts.Select(part => char.ToUpperInvariant(part[0]) + part[1..]));
        if (result.Length == 0 || !char.IsLetter(result[0]) && result[0] != '_')
        {
            result = "_" + result;
        }

        return result;
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal);

    [GeneratedRegex("^[a-z][a-z0-9_]*$", RegexOptions.CultureInvariant)]
    private static partial Regex IdRegex();

    [GeneratedRegex("^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.CultureInvariant)]
    private static partial Regex IdentifierRegex();

    [GeneratedRegex("^[A-Za-z_][A-Za-z0-9_]*(\\.[A-Za-z_][A-Za-z0-9_]*)*$", RegexOptions.CultureInvariant)]
    private static partial Regex NamespaceRegex();

    [GeneratedRegex("[^A-Za-z0-9_]+", RegexOptions.CultureInvariant)]
    private static partial Regex NonIdentifierRegex();
}
