[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$workspaceRoot = Split-Path -Parent $PSScriptRoot
$godotRoot = Join-Path $workspaceRoot "godot_project"
$toolchain = Get-Content -LiteralPath (Join-Path $PSScriptRoot "toolchain.json") -Raw -Encoding UTF8 | ConvertFrom-Json
$gameManifestPath = Join-Path $godotRoot "content\game\game-manifest.json"
$gameManifest = Get-Content -LiteralPath $gameManifestPath -Raw -Encoding UTF8 | ConvertFrom-Json

function Get-LxRelativePath([string]$basePath, [string]$path) {
    $baseFull = [System.IO.Path]::GetFullPath($basePath).TrimEnd("\", "/") +
        [System.IO.Path]::DirectorySeparatorChar
    $pathFull = [System.IO.Path]::GetFullPath($path)
    if (-not $pathFull.StartsWith($baseFull, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Path '$pathFull' is outside '$baseFull'."
    }
    return $pathFull.Substring($baseFull.Length).Replace("\", "/")
}

function Add-LubanGeneratedHeader([string]$directory, [string]$version) {
    $files = Get-ChildItem -LiteralPath $directory -Filter "*.cs" -File -Recurse
    foreach ($file in $files) {
        $content = [System.IO.File]::ReadAllText($file.FullName)
        [System.IO.File]::WriteAllText(
            $file.FullName,
            "// <auto-generated by Luban $version for LXFramework />`n#nullable disable`n" + $content.Replace("`r`n", "`n"),
            [System.Text.UTF8Encoding]::new($false))
    }
    return @($files)
}

function Get-LubanOutputHash([string[]]$directories) {
    $builder = [System.Text.StringBuilder]::new()
    foreach ($directory in $directories) {
        $files = Get-ChildItem -LiteralPath $directory -File -Recurse | Sort-Object FullName
        foreach ($file in $files) {
            [void]$builder.Append((Get-LxRelativePath $directory $file.FullName)).Append("`n")
            $fileHex = [System.BitConverter]::ToString([System.IO.File]::ReadAllBytes($file.FullName)).Replace("-", "")
            [void]$builder.Append($fileHex).Append("`n")
        }
    }
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($builder.ToString())
    $hash = [System.Security.Cryptography.SHA256]::Create()
    try {
        return [System.BitConverter]::ToString($hash.ComputeHash($bytes)).Replace("-", "").ToLowerInvariant()
    }
    finally {
        $hash.Dispose()
    }
}

$lubanAssembly = $env:LX_LUBAN_DLL
if ([string]::IsNullOrWhiteSpace($lubanAssembly)) {
    $lubanAssembly = Join-Path $workspaceRoot ".tools\luban\$($toolchain.version)\$($toolchain.assembly)"
}
if (-not (Test-Path -LiteralPath $lubanAssembly -PathType Leaf)) {
    & (Join-Path $PSScriptRoot "install-luban.ps1")
    if ($LASTEXITCODE -ne 0) {
        exit $LASTEXITCODE
    }
    $lubanAssembly = Join-Path $workspaceRoot ".tools\luban\$($toolchain.version)\$($toolchain.assembly)"
}

$reportRoot = Join-Path $godotRoot ".lx\luban"
$stagingRoot = Join-Path $reportRoot "staging"
$resolvedReportRoot = [System.IO.Path]::GetFullPath($reportRoot).TrimEnd("\", "/")
$resolvedStagingRoot = [System.IO.Path]::GetFullPath($stagingRoot)
$reportPrefix = $resolvedReportRoot + [System.IO.Path]::DirectorySeparatorChar
if (-not $resolvedStagingRoot.StartsWith($reportPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Unsafe Luban staging path '$resolvedStagingRoot'."
}
if (Test-Path -LiteralPath $resolvedStagingRoot) {
    Remove-Item -LiteralPath $resolvedStagingRoot -Recurse -Force
}

$stagingCode = Join-Path $resolvedStagingRoot "code"
$stagingData = Join-Path $resolvedStagingRoot "data"
New-Item -ItemType Directory -Path $stagingCode -Force | Out-Null
New-Item -ItemType Directory -Path $stagingData -Force | Out-Null

dotnet $lubanAssembly `
    -t client `
    -c cs-bin `
    -d bin `
    --conf (Join-Path $PSScriptRoot "luban.conf") `
    -x code.lineEnding=lf `
    -x outputCodeDir=$stagingCode `
    -x outputDataDir=$stagingData `
    -x bin.fileExt=bytes
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

$generatedCode = Add-LubanGeneratedHeader $stagingCode ([string]$toolchain.version)

$repeatRoot = Join-Path $reportRoot "determinism"
if (Test-Path -LiteralPath $repeatRoot) {
    Remove-Item -LiteralPath $repeatRoot -Recurse -Force
}
$repeatCode = Join-Path $repeatRoot "code"
$repeatData = Join-Path $repeatRoot "data"
New-Item -ItemType Directory -Path $repeatCode -Force | Out-Null
New-Item -ItemType Directory -Path $repeatData -Force | Out-Null
dotnet $lubanAssembly `
    -t client `
    -c cs-bin `
    -d bin `
    --conf (Join-Path $PSScriptRoot "luban.conf") `
    -x code.lineEnding=lf `
    -x outputCodeDir=$repeatCode `
    -x outputDataDir=$repeatData `
    -x bin.fileExt=bytes
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}
[void](Add-LubanGeneratedHeader $repeatCode ([string]$toolchain.version))
$firstOutputHash = Get-LubanOutputHash @($stagingCode, $stagingData)
$repeatOutputHash = Get-LubanOutputHash @($repeatCode, $repeatData)
if ($firstOutputHash -ne $repeatOutputHash) {
    throw "Luban output is not deterministic: $firstOutputHash != $repeatOutputHash"
}
Remove-Item -LiteralPath $repeatRoot -Recurse -Force

$compileProject = Join-Path $resolvedStagingRoot "Luban.Generated.Compile.csproj"
$coreProject = Join-Path $godotRoot "src\LXFramework.Core\LXFramework.Core.csproj"
$compileXml = @"
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$coreProject" />
  </ItemGroup>
</Project>
"@
[System.IO.File]::WriteAllText($compileProject, $compileXml, [System.Text.UTF8Encoding]::new($false))
dotnet build $compileProject --nologo --verbosity quiet
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

$negativeRoot = Join-Path $resolvedStagingRoot "negative-reference"
$negativeSchema = Join-Path $negativeRoot "schema"
$negativeData = Join-Path $negativeRoot "data"
New-Item -ItemType Directory -Path $negativeSchema -Force | Out-Null
New-Item -ItemType Directory -Path $negativeData -Force | Out-Null
Copy-Item -LiteralPath (Join-Path $PSScriptRoot "schema\design.xml") -Destination $negativeSchema
Copy-Item -Path (Join-Path $PSScriptRoot "data\*") -Destination $negativeData -Force
Copy-Item -LiteralPath (Join-Path $PSScriptRoot "fixtures\invalid\missing_reference.json") `
    -Destination (Join-Path $negativeData "design_item.json") -Force
Copy-Item -LiteralPath (Join-Path $PSScriptRoot "luban.conf") -Destination $negativeRoot
$negativeLog = Join-Path $negativeRoot "expected-failure.log"
dotnet $lubanAssembly `
    -t client `
    -c cs-bin `
    -d bin `
    --conf (Join-Path $negativeRoot "luban.conf") `
    -x outputCodeDir=(Join-Path $negativeRoot "code") `
    -x outputDataDir=(Join-Path $negativeRoot "output") `
    -x bin.fileExt=bytes *> $negativeLog
$negativeExitCode = $LASTEXITCODE
if ($negativeExitCode -eq 0) {
    throw "Luban missing-reference fixture unexpectedly passed validation."
}

$hasProduct = -not [string]::IsNullOrWhiteSpace([string]$gameManifest.name)
if ($hasProduct) {
    $finalCode = Join-Path $godotRoot ([string]$gameManifest.sourceRoot)
    $finalCode = Join-Path $finalCode "Generated\Luban"
    $finalData = Join-Path $godotRoot "content\data\luban"
}
else {
    $finalCode = Join-Path $reportRoot "generated\code"
    $finalData = Join-Path $reportRoot "generated\data"
}

foreach ($target in @($finalCode, $finalData)) {
    $resolvedTarget = [System.IO.Path]::GetFullPath($target)
    $productGeneratedRoot = if ($hasProduct) {
        [System.IO.Path]::GetFullPath((Join-Path (Join-Path $godotRoot ([string]$gameManifest.sourceRoot)) "Generated"))
    }
    else {
        $resolvedReportRoot
    }
    $allowedPrefix = $productGeneratedRoot.TrimEnd("\", "/") + [System.IO.Path]::DirectorySeparatorChar
    $contentGeneratedRoot = [System.IO.Path]::GetFullPath((Join-Path $godotRoot "content\data"))
    $contentPrefix = $contentGeneratedRoot.TrimEnd("\", "/") + [System.IO.Path]::DirectorySeparatorChar
    if (-not $resolvedTarget.StartsWith($allowedPrefix, [System.StringComparison]::OrdinalIgnoreCase) -and
        -not $resolvedTarget.StartsWith($contentPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Unsafe Luban output path '$resolvedTarget'."
    }
    if (Test-Path -LiteralPath $resolvedTarget) {
        Remove-Item -LiteralPath $resolvedTarget -Recurse -Force
    }
    New-Item -ItemType Directory -Path $resolvedTarget -Force | Out-Null
}

Copy-Item -Path (Join-Path $stagingCode "*") -Destination $finalCode -Recurse -Force
Copy-Item -Path (Join-Path $stagingData "*") -Destination $finalData -Recurse -Force

$sourceFiles = Get-ChildItem -LiteralPath $PSScriptRoot -File -Recurse |
    Where-Object { $_.FullName -notlike "*\output\*" } |
    Sort-Object FullName
$hashBuilder = [System.Text.StringBuilder]::new()
foreach ($file in $sourceFiles) {
    $relative = Get-LxRelativePath $PSScriptRoot $file.FullName
    [void]$hashBuilder.Append($relative).Append("`n")
    [void]$hashBuilder.Append([System.IO.File]::ReadAllText($file.FullName)).Append("`n")
}
$hashBytes = [System.Text.Encoding]::UTF8.GetBytes($hashBuilder.ToString())
$sha256 = [System.Security.Cryptography.SHA256]::Create()
try {
    $inputHash = [System.BitConverter]::ToString($sha256.ComputeHash($hashBytes)).Replace("-", "").ToLowerInvariant()
}
finally {
    $sha256.Dispose()
}

$dataFiles = Get-ChildItem -LiteralPath $finalData -Filter "*.bytes" -File -Recurse |
    Sort-Object FullName |
    ForEach-Object { Get-LxRelativePath $finalData $_.FullName }
$manifest = [ordered]@{
    schemaVersion = 1
    generator = "Luban"
    toolVersion = [string]$toolchain.version
    toolCommit = [string]$toolchain.commit
    dataFormat = "bin"
    fileExtension = ".bytes"
    inputHash = $inputHash
    outputHash = $firstOutputHash
    files = @($dataFiles)
}
$manifestPath = Join-Path $finalData "luban-manifest.json"
[System.IO.File]::WriteAllText(
    $manifestPath,
    ($manifest | ConvertTo-Json -Depth 5) + "`n",
    [System.Text.UTF8Encoding]::new($false))

$report = [ordered]@{
    validatedAtUtc = [DateTimeOffset]::UtcNow.ToString("O", [System.Globalization.CultureInfo]::InvariantCulture)
    success = $true
    toolVersion = [string]$toolchain.version
    toolCommit = [string]$toolchain.commit
    toolAssembly = [System.IO.Path]::GetFullPath($lubanAssembly)
    dataFormat = "bin"
    fileExtension = ".bytes"
    inputHash = $inputHash
    outputHash = $firstOutputHash
    generatedCodeCompiled = $true
    negativeReferenceRejected = $true
    product = if ($hasProduct) { [string]$gameManifest.name } else { $null }
    codeOutput = Get-LxRelativePath $godotRoot $finalCode
    dataOutput = Get-LxRelativePath $godotRoot $finalData
    codeFiles = @($generatedCode | ForEach-Object { Get-LxRelativePath $stagingCode $_.FullName })
    dataFiles = @($dataFiles)
}
New-Item -ItemType Directory -Path $reportRoot -Force | Out-Null
[System.IO.File]::WriteAllText(
    (Join-Path $reportRoot "report.json"),
    ($report | ConvertTo-Json -Depth 6) + "`n",
    [System.Text.UTF8Encoding]::new($false))

Write-Host "Luban data passed: $($generatedCode.Count) code file(s), $($dataFiles.Count) data file(s) -> $($report.dataOutput)"

# The intentional negative-reference probe leaves its native process exit code non-zero.
# Publish the aggregate script result instead so callers continue after a successful data gate.
$global:LASTEXITCODE = 0
